title: Cole Boyer
theme: jekyll-theme-minimal
description: Seeking full time employment in the field of Information Technology.  Five years of experience in IT Support and System Administration.  Ten years of experience with customer service and support.